@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Система мониторинга фермы — Альтернативное решение (C1)

Person(operator, "Оператор фермы", "Просматривает данные, получает уведомления")
Person(onsite, "Оператор по наблюдению за животными", "Получает локальные тревоги при обрыве связи")
Person(admin, "Администратор системы", "Управляет пользователями и метриками")

System(platform, "Платформа мониторинга поголовья", "Облачная обработка")
System(agents, "Фермерские агенты без ИИ", "Локальные агенты")
System(ferma_platform, "Центральный узел фермы", "Агрегация и размещенный ИИ")

System_Ext(equipment, "Оборудование фермы", "Камеры, кормушки, датчики, фильтры")
System_Ext(external, "Внешние системы", "ERP, BI, аналитика")
System_Ext(app, "Мобильное/веб-приложение", "Клиент через API")
System_Ext(mobile, "4G/(PTP/PTMP)", "Резернвый канал связи")
System_Ext(mobile, "PTP/PTMP", "Альтернативный канал связи")

Rel(operator, platform, "Получает данные и уведомления")
Rel(onsite, platform, "Получает базовые локальные оповещения (без ИИ)")
Rel(admin, platform, "Управление доступом и метриками")

Rel(agents, equipment, "Сбор данных, управление (при наличии связи)")
Rel(platform, app, "Предоставляет API")
Rel(platform, external, "Экспортирует метрики")
Rel(ferma_platform, platform, "Экспортирует метрики")
Rel(agents, mobile, "Экстренные уведомления при разрывах связи")

Rel(agents, ferma_platform, "Данные агентов")

@enduml